import os
from dotenv import load_dotenv

load_dotenv()

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
AIRTABLE_API_KEY = os.getenv("AIRTABLE_API_KEY")
AIRTABLE_BASE_ID = os.getenv("AIRTABLE_BASE_ID")
AIRTABLE_TABLE_NAME = os.getenv("AIRTABLE_TABLE_NAME", "Leads")
APIFY_API_KEY = os.getenv("APIFY_API_KEY")
CALENDLY_LINK = os.getenv("CALENDLY_LINK")
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL", "")
SUMMARY_EMAIL = os.getenv("SUMMARY_EMAIL", "")

CLAUDE_MODEL = "claude-sonnet-4-20250514"

QUALIFIER_SCORE_THRESHOLD = 70
BUYING_SIGNAL_MIN_EXCHANGES = 3

RETRY_ATTEMPTS = 3
RETRY_BASE_DELAY = 1.0
